// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, created_at, updated_at, expires_at, revoked_at, user_id)
VALUES (
    $1,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC' + INTERVAL '60 days',
    NULL,
    $2
)
RETURNING token
`

type CreateRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const refreshTokenLookup = `-- name: RefreshTokenLookup :one
SELECT expires_at, revoked_at, user_id FROM refresh_tokens
WHERE token = $1
`

type RefreshTokenLookupRow struct {
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

func (q *Queries) RefreshTokenLookup(ctx context.Context, token string) (RefreshTokenLookupRow, error) {
	row := q.db.QueryRowContext(ctx, refreshTokenLookup, token)
	var i RefreshTokenLookupRow
	err := row.Scan(&i.ExpiresAt, &i.RevokedAt, &i.UserID)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW() AT TIME ZONE 'UTC', updated_at = NOW() AT TIME ZONE 'UTC'
WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
