// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, created_at, updated_at, expires_at, revoked_at, user_id)
VALUES (
    $1,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC' + INTERVAL '60 days',
    NULL,
    $2
)
RETURNING token
`

type CreateRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const refreshTokenLookup = `-- name: RefreshTokenLookup :one
SELECT expires_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) RefreshTokenLookup(ctx context.Context, token string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, refreshTokenLookup, token)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}
